### ISSUE TITLE
Great work! How to use for 2 player settings (like Elo / Glicko2)?

### ISSUE THREAD

**Issue by kb-open** [duhby/elommr#1]
Great work! How to use for 2 player settings (like Elo / Glicko2)?

**Comment by duhby** [comment]
The [example](https://github.com/duhby/elommr?tab=readme-ov-file#quick-example) in the readme works for that since there are only 2 players in the "competition" list.

**Comment by kb-open** [comment]
What does the tuple `(player1, 0, 0)` in `standings` signify?  
Frankly, I couldn't understand the meaning of code comment "Range of players that got or tied for first".

If I assume that it means that player1 scored 0 in the contest and 0 in the match, then what's the difference between a contest and a match?

Kindly explain @duhby

**Comment by duhby** [comment]
Elommr was originally designed for rating a lot of players that ranked on leaderboards during contests (like codeforces for example) and it's possible for some players to get the same amount of points in a given contest, so there needs to be a way to show how many players tied. 

Example: 
```
# Contest leaderboard
# Bob: 150
# Bill: 125
# Joe: 125
# Jane: 100
```
Here you would say that Bob is in range (0, 0) because he's in first place and no one is tied with him. Bill and Joe would both be in the range (1, 2) since it wouldn't be fair to say one performed better than the other, and Jane would be in range (3, 3).

If you just need to compare 2 players against each other, then you only need to say the winning player's range is (0, 0) and the losing player's range is (1, 1).

**Comment by kb-open** [comment]
Understood. Thanks!
One follow-up question though. If the leaderboard would have been like this:
```
# Contest leaderboard
# Bob: 150
# Bill: 125
# Joe: 125
# Jane: 100
# Adam: 100
# Alice: 100
# Maya: 75
# Charlie: 75
```
Will the standings be like below?
```
[(Bob, 0, 0), (Bill, 1, 2), (Joe, 1, 2), (Jane, 3, 5), (Adam, 3, 5), (Alice, 3, 5), (Maya, 6, 7), (Charlie, 6, 7)]
```

**Comment by duhby** [comment]
No, the people with 100 points would all have the *range* (3, 5), and it's inclusive so you wouldn't say 6. And then Maya and Charlier (both with 75 points) would get the range (6, 7). The others were correct though.

**Comment by kb-open** [comment]
Cool. Updated my previous comment. Hope it is correct now.
Thanks a ton!

**Comment by kb-open** [comment]
I could run through a few examples now. 
So, I have a few more follow-up questions. Hope I'm not asking too many questions:

- Assume that we have a 2-player game with 1000 overall players playing in parallel. Must we do `round_update` with `standings` of all 1000 players after each match? Or would it suffice to do many sequential `round_update`s with `standings` of only the 2 players who played in each of those matches?
- If we go for the second option, the `place` variable `event_history` will track the player's match-specific place, and not the player's overall place in the leaderboard. Hope that this is a correct usage of the method?
- What's the difference between `rating_mu` and `perf_score` in `event_history`?
- Can Elo-MMR provide probability that a 2-player will be draw (like TrueSkill provides)? Basically, I'm looking for a metric for quality / fairness of a 2-player match.

**Comment by duhby** [comment]
- If you're doing separate 1v1 matches, you should call round update with just the 2 players that were against each other. 
- That is correct, since the placement only matters for that specific "contest" or match.
- `rating_mu` is the player's overall rating while `perf_score` is the performance score of a player for a specific match. So `rating_mu` is the main rating like the single number you have for a player when using the Elo rating system.
- Yes, I actually asked the original creator about this a while ago, here was his response: 
> In 1v1, Elo-MMR is pretty similar to Glicko1 (which avoids the flaw our paper mentions with Glicko2). If two players have a skill difference of S, then the win probability will be given by the inverse CDF at S of a logistic distribution with mean 0 and variance 2\*beta\*beta. When the rating difference is R, the calculation is similar, evaluating the CDF at R, but with a higher variance of 2\*beta\*beta + sigma_1\*sigma_1 + sigma_2\*sigma_2 to account for the fact that we don't know their actual skills. See the win_probability() method in an earlier version of the code:

[The function he was referring to](https://github.com/EbTech/Elo-MMR/blob/8849c6cdbe36737466203d9f28c3a5d8c6c27a63/ranking/src/systems/elo_mmr.rs#L183-L191)

~~I converted it to Python too for my own project, but I guess I should add it to the library as well.~~ I actually already added it, it's called `win_probability`.

**Comment by kb-open** [comment]
Awesome! Thanks!
However, I tried the following code:
```
from elommr import EloMMR, Player, win_probability
# Create player
p1 = Player()
p2 = Player()
if win_probability(p1, p2) > 0.50 or win_probability(p2, p1) > 0.50:
    print('This match seems to be not so fair')
```

This gives the following error:
```
AttributeError                            Traceback (most recent call last)

[<ipython-input-24-7a1d37aa581e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 if win_probability(p1, p2) > 0.50 or win_probability(p2, p1) > 0.50:
      2     print('This match seems to be not so fair')

[/usr/local/lib/python3.10/dist-packages/elommr/elommr.py](https://localhost:8080/#) in win_probability(player, foe, contest_weight, sig_perf)
    527     """
    528     sig_perf = sig_perf / math.sqrt(contest_weight)
--> 529     sigma = math.sqrt(player.sig**2 + foe.sig**2 + 2 * sig_perf**2)
    530     z = (player.mu - foe.mu) / sigma
    531     return 0.5 + 0.5 * math.tanh(0.5 * TANH_MULTIPLIER * z)  # Logistic distribution

AttributeError: 'Player' object has no attribute 'sig'
```
By the way, when I print `p1` or `p2`, I see the following structure:
`Player(mu=1500, sig=350)`

So, `sig` is present in `Player`, but probably you need to access it differently inside your `win_probability` code?

**Comment by kb-open** [comment]
In addition to the above error, I have one more question. How do we convert win probability to draw probability? For now, I'm using a hack like below:
```
if win_probability(p1, p2) > 0.50 or win_probability(p2, p1) > 0.50:
    print('This match seems to be not so fair')
```
But ideally, a function like below would be better (which TrueSkill provides):
```
if draw_probability(p1, p2) < 0.50:
    print('This match seems to be not so fair')
```

**Comment by duhby** [comment]
> Awesome! Thanks!
> However, I tried the following code:
> ```
> from elommr import EloMMR, Player, win_probability
> # Create player
> p1 = Player()
> p2 = Player()
> if win_probability(p1, p2) > 0.50 or win_probability(p2, p1) > 0.50:
>     print('This match seems to be not so fair')
> ```
> 
> This gives the following error:
> ``` 
> AttributeError: 'Player' object has no attribute 'sig'
> ```


That's because win_probability takes in `Rating` objects, not `Player` objects (as you can see in the docstring and type definition). If you look at the docstring for `Player` you'll see that `Player.approx_posterior` is the current rating value without rounding.

> By the way, when I print `p1` or `p2`, I see the following structure:
> `Player(mu=1500, sig=350)`

That's because the repr function of `Player` gets the mu and sig values from the most recent contest in `event_history` or from `approx_posteterior` if the player hasn't played in any contests. There aren't actually direct mu and sig attributes.

**Comment by duhby** [comment]
> In addition to the above error, I have one more question. How do we convert win probability to draw probability? For now, I'm using a hack like below:
> ```
> if win_probability(p1, p2) > 0.50 or win_probability(p2, p1) > 0.50:
>     print('This match seems to be not so fair')
> ```

This would only be False if both players had the exact same Rating.

> But ideally, a function like below would be better (which TrueSkill provides):
> ```
> if draw_probability(p1, p2) < 0.50:
>     print('This match seems to be not so fair')
> ```

I'm not sure how a draw probability would work, since if both players had the same rating the probability would have to be 1, but then that'd be assuming that there's a 0% chance of either person winning, which is why win probability makes more sense and is easier to define.

If you want to make your matches fair, you can do something like this since a win probability of .5 means the fairest possible match:
```py
prob = win_probability(r1, r2)
dist = abs(.5 - prob)  # distance from .5
if dist > .2:  # adjustable value
    print("unfair")
```
